### ISSUE TITLE
Python API is not returning whitelisted validation for IPv4

### ISSUE THREAD

**Issue by kiennt23** [AlienVault-OTX/OTX-Python-SDK#54]
I used the below code to get indicator details for this IP address (8.8.8.8)
`result = otx_client.get_indicator_details_by_section(IndicatorTypes.IPv4, '8.8.8.8', 'general')`

But it doesn't return the whitelisted validation as in the example
![Screenshot 2020-07-20 at 2 00 13 PM](https://user-images.githubusercontent.com/11470413/87904666-60200000-ca91-11ea-96ad-72b14a5f3721.png)

If I use the other API, it returns the whitelisted validation successfully
`validation = otx_client.validate_indicator(IndicatorTypes.IPv4, '8.8.8.8')`
![Screenshot 2020-07-20 at 2 02 15 PM](https://user-images.githubusercontent.com/11470413/87904790-a4130500-ca91-11ea-9012-1399def1ffc1.png)

**Comment by rustybrooks** [comment]
You're right.  I'm fixing it, should be out today/tomorrow (no need to update the SDK, the fix is server side)
