### ISSUE TITLE
Error 504 triying to get indicators

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [AlienVault-OTX/OTX-Python-SDK#63]
Hi:

Triying to use indicators and recieving error 504, I switch to basic testing with curl to debug the problem and still get 504

`curl "https://otx.alienvault.com/api/v1/indicators/export?modified_since=2022-02-25T12:35:00+00:00&limit=50&page=1" -H "X-OTX-API-KEY: XXX"
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
`

Not able to get results, don't know the proble, but it looks like something not working as expected.
Can anybody help here?

**Comment by ghost** [comment]
The whole plattform seems down for a while now. When did you first notice?
https://cybersecurity.att.com/open-threat-exchange  gives only nginx default page.

**Comment by BernaldoPenasAntelo** [comment]
Hi:
you're right, now it's working ... 

Best regards.
